# Generated by Django 5.2.3 on 2025-07-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(max_length=255, verbose_name="ID продукта Stripe"),
                ),
                (
                    "stripe_price_id",
                    models.CharField(max_length=255, verbose_name="ID цены Stripe"),
                ),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_details",
                        to="materials.course",
                        verbose_name="курс",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_details",
                        to="materials.lesson",
                        verbose_name="урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Продукт/Цена",
                "verbose_name_plural": "Stripe Продукты/Цены",
            },
        ),
    ]
